# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estTheta <- function(E, U, R, lag, A, Gam, Psi, delta, wgt, fR, fEX, Psiprob, minWgt, maxWgt, censor_expXbetaG0, censor_expXbetaG1, censor_LambdaTB, censor_LambdaTU, censor_LambdaR, unBlind_expXbeta, unBlind_LambdaT, timesB, timesU, gFunc, group, v, theta, type) {
    .Call(`_VEwaningVariant_estTheta`, E, U, R, lag, A, Gam, Psi, delta, wgt, fR, fEX, Psiprob, minWgt, maxWgt, censor_expXbetaG0, censor_expXbetaG1, censor_LambdaTB, censor_LambdaTU, censor_LambdaR, unBlind_expXbeta, unBlind_LambdaT, timesB, timesU, gFunc, group, v, theta, type)
}

gFunction <- function(gFunc, u, theta, knots) {
    .Call(`_VEwaningVariant_gFunction`, gFunc, u, theta, knots)
}

